usersactivity/urls.py
from django.urls import path
from django.urls import reverse
from . import views



app_name = 'usersactivity'
urlpatterns = [
    path('login', views.user_login, name='login'),
    path('signup', views.sign_up, name='sign_up'),
    path('profile', views.user_profile, name='profile'),
    path('logout', views.user_logout, name='logout'),
    path('change_password', views.change_user_password, name='change_password'),
    path('profile_update', views.update_profile, name='profile_update'),


]

usersproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import(
	PasswordResetView, PasswordResetConfirmView,
    PasswordResetDoneView, PasswordResetCompleteView
   	)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usersactivity/', include('usersactivity.urls')),
    path('forgot_password/', PasswordResetView.as_view(
    	template_name='usersactivity/forgot_password.html'), name='forgot_password'),
    path('password_reset_done', PasswordResetDoneView.as_view(
    	template_name='usersactivity/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    	template_name='usersactivity/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', PasswordResetCompleteView.as_view(
    	template_name='usersactivity/password_reset_complete.html'), name='password_reset_complete'),


]

usersactivity/models.py
from django.db import models

# Create your models here.

usersactivity/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from crispy_forms.helper import FormHelper


class SignupForm(UserCreationForm):
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']
		labels = {'email':'Email'}
		help_texts = {

            'username': None,
        }


class UpdateProfileForm(UserChangeForm):
	password = None
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']
		help_texts = {

            'username': None,
        }

usersactivity/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from .forms import SignupForm, UpdateProfileForm
from django.contrib import messages
from django.contrib.auth.forms import(
	AuthenticationForm,
	PasswordChangeForm
	)
from django.contrib.auth import(
	authenticate, login, update_session_auth_hash,
	logout
	)
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User


def sign_up(request):
	if request.method == 'POST':
		sign_up_form = SignupForm(request.POST)
		if sign_up_form.is_valid():
			sign_up_form.save()
			return HttpResponseRedirect('login')
	else:
		sign_up_form = SignupForm()

	return render(request, 'usersactivity/sign_up.html', {'form':sign_up_form})


def user_login(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.success(request,'logged in successfully')
				#return render(request, 'usersactivity/profile.html')
				return HttpResponseRedirect('profile')
	else:
		form = AuthenticationForm()
	return render(request, 'usersactivity/login.html', {'form':form})


def user_profile(request):
	if request.user.is_authenticated:
		context ={
			'name': request.user.get_full_name(),
			'first_name': request.user.first_name,
			'email': request.user.email,
		}
	else:
		return HttpResponseRedirect('login')
	return render(request, 'usersactivity/profile.html', context)


def user_logout(request):
	logout(request)
	return HttpResponseRedirect('login')


def change_user_password(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			form = PasswordChangeForm(user=request.user, data=request.POST)
			if form.is_valid():
				form.save()
				update_session_auth_hash(request, form.user)
				return HttpResponseRedirect('profile')
		else:
			form = PasswordChangeForm(user=request.user)
		return render(request, 'usersactivity/change_password.html', {'form':form})
	else:
		return HttpResponseRedirect('login')


def update_profile(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			form = UpdateProfileForm(request.POST, instance=request.user)
			if form.is_valid():
				form.save()
		else:
			form = UpdateProfileForm(instance=request.user)
		return render(request, 'usersactivity/profile_update.html', {'form':form})
	else:
		HttpResponseRedirect('login')

templates/usersactivity/base.html
<!DOCTYPE html>
<html>
<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<title>mysite</title>
	<style type="text/css">
		#hint_id_password1{
			display: none;
		}
		#hint_id_new_password1{
			display: none;
		}

	</style>
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

templates/usersactivity/change_password.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	
<div class="col-md-6 bg-light container  px-3 py-5 ">
	<form  method="post" class="" style="display: inline;" >
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button  type="submit" class="btn btn-outline-success" >Change</button>
</form>



</div>


{% endblock %}

templates/usersactivity/forgot_password.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 bg-light container mt-5 px-5 py-5 ">
	<form  method="post" class="form-group px-5">
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button type="submit" class="btn btn-outline-success">Change</button>
</form>

</div>

{% endblock %}

templates/usersactivity/login.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 bg-light container mt-5 px-5 py-5 ">
	<form  method="post" class="form-group px-5">
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button type="submit" class="btn btn-outline-success">Login</button>
</form>
<a class="mr-3 ml-5" href="{% url 'usersactivity:sign_up' %}">Sign_Up</a>
<a class="text-danger" href="{% url 'forgot_password' %}">forgot password</a>

</div>

{% endblock %}

templates/usersactivity/password_reset_complete.html
{% extends 'usersactivity/base.html' %}

{% block content %}
<div  class="container bg-light text-primary mt-5 px-5 py-5 text-center">
	<h4>Congratulations !!!!</h4>
	
	<h4>password reset successfully !!!!</h4>
	<a href="{% url 'usersactivity:login' %}" class="btn btn-success">Login</a>
</div>
{% endblock %}

templates/usersactivity/password_reset_confirm.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 bg-light container mt-5 px-5 py-5 ">
	<form  method="post" class="form-group px-5">
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button type="submit" class="btn btn-outline-success">Reset</button>
</form>

</div>

{% endblock %}

templates/usersactivity/password_reset_done.html
{% extends 'usersactivity/base.html' %}

{% block content %}
<div  class="container bg-light text-primary mt-5 px-5 py-5 text-center">
	
	
	<h4>Email has been sent please check !!</h4>
	
</div>
{% endblock %}

templates/usersactivity/profile.html
{% extends 'usersactivity/base.html' %}

{% block content %}

{% if messages %}

{% for message in messages %}
<p>{{message}}</p>
{% endfor %}

{% endif %}
<div  class="container bg-light text-primary mt-5 px-5 py-5 text-center">

	<table>
		<tr >
			<td><h4 class="ml-5">Welcome {{request.user.first_name}}</h4></td>
		</tr>
			<tr>
			<td><h6>NAME : </h6></td>
			<td><h6>{{request.user.get_full_name}}</h6></td>

		</tr>


			<tr>
			<td><h6>EMAIL : </h6></td>
			<td><h6>{{request.user.email}}</h6></td>

		</tr>


			<tr>
			<td><a class="btn btn-outline-success" href="{% url 'usersactivity:logout' %}">Logout</a>
</td>
			<td><a class="btn btn-outline-warning" href="{% url 'usersactivity:profile_update' %}">Update Profile</a>
</td>
<td><a class="btn btn-outline-secondary" href="{% url 'usersactivity:change_password' %}">Change Password</a>
</td>

		</tr>
	</table>
	
	
</div>
{% endblock %}

templates/usersactivity/profile_update.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	
<div class="col-md-6 bg-light container  px-3 py-3 ">
	<form  method="post" class="" style="display: inline;" >
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button  type="submit" class="btn btn-outline-success" >Update</button>
</form>
<a class="btn btn-primary" href="{% url 'usersactivity:logout' %}">Logout</a>
</div>


{% endblock %}

templates/usersactivity/sign_up.html
{% extends 'usersactivity/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	
<div class="col-md-6 bg-light container  px-3 py-3 ">
	<form  method="post" class="" style="display: inline;" >
	{% csrf_token %}

	{% if form.non_field_errors %}
	{% for error in form.non_field_errors %}
	<p class="text-danger">{{error}}</p>
	{% endfor %}
	{% endif %}

	{% for field in form %}
	 {{field|as_crispy_field}} {{ field.errors|striptags}} 
	{% endfor %}
	
	<button  type="submit" class="btn btn-outline-success" >Sign_Up</button>
</form>

<a class=" btn btn-outline-primary mr-3 ml-5" href="{% url 'usersactivity:login' %}" >Login</a>


</div>


{% endblock %}